############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/services"
weight = 2

[[main]]
name = "Our Work"
url = "/work"
weight = 3


[[main]]
name = "About"
url = "/about"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6


# footer menu

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3